/* Auto-generated by website/build.py — do not hand-edit. */

window.TRIP = {
  "name": "Nepal Workation 2026",
  "depart": "2026-05-09",
  "return": "2026-05-23",
  "nights": 14,
  "travellers": 2,
  "vehicle": "Mahindra Thar Roxx (Thar Digital Services — sole prop on mom's PAN)",
  "capDays": 30,
  "permitDaysUsed": 18,
  "totalKm": 4410
};

window.ITINERARY = [
  {
    "day": 1,
    "date": "2026-05-09",
    "weekday": "Sat",
    "leg": "Bikaner → Noida",
    "km": 610,
    "hours": "9–10",
    "halt": "Noida",
    "type": "drive",
    "note": "Early start 5 AM. NH11 + Western Peripheral Expressway."
  },
  {
    "day": 2,
    "date": "2026-05-10",
    "weekday": "Sun",
    "leg": "Noida → Gorakhpur",
    "km": 720,
    "hours": "10–11",
    "halt": "Gorakhpur",
    "type": "drive",
    "note": "Yamuna + Agra-Lucknow + Purvanchal + Gorakhpur Link."
  },
  {
    "day": 3,
    "date": "2026-05-11",
    "weekday": "Mon",
    "leg": "Gorakhpur → Sunauli → Bhairahawa",
    "km": 120,
    "hours": "4–5",
    "halt": "Bhairahawa",
    "type": "border",
    "note": "Bhansar + Yatayat + SIM. Light Lumbini if time. Evening work."
  },
  {
    "day": 4,
    "date": "2026-05-12",
    "weekday": "Tue",
    "leg": "Bhairahawa → Pokhara",
    "km": 190,
    "hours": "6–7",
    "halt": "Pokhara",
    "type": "drive",
    "note": "Smooth highway. Half work day on arrival."
  },
  {
    "day": 5,
    "date": "2026-05-13",
    "weekday": "Wed",
    "leg": "Pokhara — work day",
    "km": 0,
    "hours": "—",
    "halt": "Pokhara",
    "type": "work",
    "note": "Buy ACAP online (epermit.ntnc.org.np) OR at Pokhara counter — at-checkpost surcharge is DOUBLE. Lakeside dinner."
  },
  {
    "day": 6,
    "date": "2026-05-14",
    "weekday": "Thu",
    "leg": "Pokhara → Beni / Tatopani",
    "km": 85,
    "hours": "4–5",
    "halt": "Beni / Tatopani",
    "type": "acclimatise",
    "note": "Half work morning. Hot spring evening."
  },
  {
    "day": 7,
    "date": "2026-05-15",
    "weekday": "Fri",
    "leg": "Beni → Jomsom (4×4)",
    "km": 75,
    "hours": "5–6",
    "halt": "Jomsom",
    "type": "offroad",
    "note": "The real test. 4WD-Low. Sleep at 2,700 m to acclimatise."
  },
  {
    "day": 8,
    "date": "2026-05-16",
    "weekday": "Sat",
    "leg": "Jomsom → Muktinath darshan → Jomsom",
    "km": 40,
    "hours": "3–4",
    "halt": "Jomsom",
    "type": "darshan",
    "note": "Pre-dawn start. No work today."
  },
  {
    "day": 9,
    "date": "2026-05-17",
    "weekday": "Sun",
    "leg": "Jomsom → Pokhara",
    "km": 160,
    "hours": "7–8",
    "halt": "Pokhara",
    "type": "drive",
    "note": "Long descent. Recover."
  },
  {
    "day": 10,
    "date": "2026-05-18",
    "weekday": "Mon",
    "leg": "Pokhara — work day",
    "km": 0,
    "hours": "—",
    "halt": "Pokhara",
    "type": "work",
    "note": "Lakeside cafe with fibre."
  },
  {
    "day": 11,
    "date": "2026-05-19",
    "weekday": "Tue",
    "leg": "Pokhara — work + leisure",
    "km": 0,
    "hours": "—",
    "halt": "Pokhara",
    "type": "leisure",
    "note": "Sarangkot sunrise / Davis Falls / boating."
  },
  {
    "day": 12,
    "date": "2026-05-20",
    "weekday": "Wed",
    "leg": "Pokhara — work day",
    "km": 0,
    "hours": "—",
    "halt": "Pokhara",
    "type": "work",
    "note": "Pre-departure laundry, doc review."
  },
  {
    "day": 13,
    "date": "2026-05-21",
    "weekday": "Thu",
    "leg": "Pokhara → Bhairahawa",
    "km": 190,
    "hours": "6–7",
    "halt": "Bhairahawa",
    "type": "drive",
    "note": "Surrender ACAP. Final Lumbini visit."
  },
  {
    "day": 14,
    "date": "2026-05-22",
    "weekday": "Fri",
    "leg": "Bhairahawa → Sunauli exit → Lucknow",
    "km": 470,
    "hours": "9–10",
    "halt": "Lucknow",
    "type": "border",
    "note": "Surrender Bhansar + Yatayat. Get exit stamp."
  },
  {
    "day": 15,
    "date": "2026-05-23",
    "weekday": "Sat",
    "leg": "Lucknow → Bikaner",
    "km": 830,
    "hours": "11–12",
    "halt": "Home",
    "type": "drive",
    "note": "Long final day. Optional split via Agra."
  }
];

window.RULES = {
  "lastUpdated": "2026-05-04",
  "verifyBefore": "2026-05-08",
  "officialSources": [
    {
      "label": "Nepal Department of Customs",
      "url": "https://www.customs.gov.np/"
    },
    {
      "label": "Nepal Department of Transport Mgmt",
      "url": "https://www.dotm.gov.np/"
    },
    {
      "label": "Nepal Department of Immigration",
      "url": "https://www.immigration.gov.np/"
    },
    {
      "label": "NTNC / ACAP",
      "url": "https://ntnc.org.np/"
    },
    {
      "label": "NTNC / ACAP e-permit",
      "url": "https://epermit.ntnc.org.np/"
    },
    {
      "label": "Nepal Tourism Board",
      "url": "https://ntb.gov.np/"
    },
    {
      "label": "Indian Embassy, Kathmandu",
      "url": "https://www.indembkathmandu.gov.in/"
    }
  ],
  "rules": [
    {
      "category": "Identity",
      "title": "Visa not required for Indians",
      "detail": "Indians enter Nepal under the 1950 Treaty of Peace and Friendship — no visa required. Carry passport (preferred) OR original ECI Voter ID; downloads/photocopies not accepted by Indian Embassy. Aadhaar and PAN are NOT on either accepted-ID list at air entry; land borders historically also accept passport/Voter ID.",
      "source": "https://www.immigration.gov.np/page/information-for-indian-nationals",
      "fetchedAt": "2026-05-04T13:16:00+05:45",
      "confidence": "official"
    },
    {
      "category": "Vehicle",
      "title": "Bhansar (Customs) daily fee",
      "detail": "Pay daily at border. 2026 figures from Gaur Customs Office (Kathmandu Post 2026-04-17): NPR 600/day four-wheelers (SUV), NPR 400/day three-wheelers, NPR 200/day motorcycles. Older Indian-consulate range was NPR 250–500/day. Pay 2–3 buffer days beyond planned exit. Confirm at Sunauli/Belahiya counter on entry — figures vary by border post.",
      "source": "https://kathmandupost.com/province-no-2/2026/04/17/madhesh-crackdown-on-indian-registered-vehicles-rattles-political-parties",
      "fetchedAt": "2026-05-04T13:16:00+05:45",
      "confidence": "corroborated"
    },
    {
      "category": "Vehicle",
      "title": "Yatayat (Transport) permit",
      "detail": "Separate permit from Bhansar, issued at border. NPR figure not corroborated by any source dated after 2026-01-01 — DOTM site is silent on tourist-vehicle entry, customs site too. Order of magnitude similar to Bhansar based on prior baseline. Confirm exact figure at Sunauli on entry.",
      "source": "https://www.dotm.gov.np/",
      "fetchedAt": "2026-05-04T13:14:00+05:45",
      "confidence": "inferred"
    },
    {
      "category": "Vehicle",
      "title": "30-day cumulative annual cap",
      "detail": "Indian-registered vehicles capped at 30 cumulative days per calendar year in Nepal. Exceeding the cap (even with paid Bhansar) → vehicle seized/auctioned. Confirmed by Indian Embassy Indian-Vehicles page and Kathmandu Post 2026-04-17.",
      "source": "https://www.indembkathmandu.gov.in/page/indian-vehicles/",
      "fetchedAt": "2026-05-04T13:17:00+05:45",
      "confidence": "official"
    },
    {
      "category": "Vehicle",
      "title": "Firm-registered SUV authorization letter",
      "detail": "For a vehicle registered to a firm (Thar Digital Services), carry an authorization letter on firm letterhead stating personal-travel use and signed by the proprietor. Without it, customs may assess under commercial slabs. Source pages do not specify exact letter format — use /docs/AUTHORIZATION_LETTER_TEMPLATE.md.",
      "source": "https://www.indembkathmandu.gov.in/page/indian-vehicles/",
      "fetchedAt": "2026-05-04T13:17:00+05:45",
      "confidence": "inferred"
    },
    {
      "category": "Vehicle",
      "title": "PUC (Pollution Under Control) certificate",
      "detail": "Customs.gov.np publishes nothing about PUC certificates for Indian vehicles entering Nepal in server-rendered HTML; Indian Embassy Indian-Vehicles page does not list it as required. No 2026 circular found mandating PUC. Carry anyway as a defensive document — minimal cost.",
      "source": "https://www.customs.gov.np/",
      "fetchedAt": "2026-05-04T13:13:00+05:45",
      "confidence": "inferred"
    },
    {
      "category": "Customs",
      "title": "Used personal electronics",
      "detail": "Laptops, phones, cameras with prior-purchase invoices = exempt as personal effects. Carry both MacBook invoices in printed form. Customs.gov.np FAQ addresses only returning Nepali residents' personal effects — figure carried forward from prior baseline.",
      "source": "https://www.customs.gov.np/faq/",
      "fetchedAt": "2026-05-04T13:35:54+05:45",
      "confidence": "inferred"
    },
    {
      "category": "Customs",
      "title": "New unboxed goods",
      "detail": "New retail items in original packaging may be assessed for duty at the green/red channel. Avoid carrying unopened electronics or new gifts. No 2026 update — carry forward.",
      "source": "https://www.customs.gov.np/",
      "fetchedAt": "2026-05-04T13:13:00+05:45",
      "confidence": "inferred"
    },
    {
      "category": "Driving",
      "title": "Left-hand drive, lights ON in mountains",
      "detail": "Nepal drives on the left (same as India). Headlights mandatory in hill sections. Speed: 40 town / 60–80 highway / 30 switchbacks. Zero-tolerance on alcohol. DOTM site has only public-transport fare notices, no foreign-driver page — carried forward from prior baseline.",
      "source": "https://www.dotm.gov.np/",
      "fetchedAt": "2026-05-04T13:14:00+05:45",
      "confidence": "inferred"
    },
    {
      "category": "Fuel",
      "title": "Mustang fuel scarcity",
      "detail": "Beni and Jomsom are the only reliable pumps en route to Muktinath. Top up at both — Tatopani and Ghasa pumps are unreliable. No 2026 source contradicts — carried forward.",
      "source": "https://www.indembkathmandu.gov.in/page/advisory-list/",
      "fetchedAt": "2026-05-04T13:17:00+05:45",
      "confidence": "inferred"
    },
    {
      "category": "Money",
      "title": "INR notes accepted",
      "detail": "INR 100/200/500 widely accepted. INR 2000 notes NOT accepted (RBI withdrew them 2023; Nepal Rastra Bank ban remains). Prefer NPR for fuel and ACAP. ATMs reliable in Pokhara/Bhairahawa; spotty in Jomsom.",
      "source": "https://www.indembkathmandu.gov.in/page/advisory-list/",
      "fetchedAt": "2026-05-04T13:17:00+05:45",
      "confidence": "inferred"
    },
    {
      "category": "Connectivity",
      "title": "NTC vs Ncell SIM",
      "detail": "NTC = better Mustang/mountain coverage. Ncell = faster Pokhara speeds but spotty in Jomsom/Muktinath. Buy NTC at Sunauli/Bhairahawa with passport+photo. Tourist SIM rules unchanged in 2026 per advisory list.",
      "source": "https://www.indembkathmandu.gov.in/page/advisory-list/",
      "fetchedAt": "2026-05-04T13:17:00+05:45",
      "confidence": "inferred"
    },
    {
      "category": "Insurance",
      "title": "Indian motor policy invalid in Nepal",
      "detail": "Indian motor insurance is invalid in Nepal. Buy Nepal third-party at Sunauli border (≈NPR 1,000–1,500 for two weeks, SUV) OR confirm Nepal rider with Indian insurer in writing before departure.",
      "source": "https://www.indembkathmandu.gov.in/page/indian-vehicles/",
      "fetchedAt": "2026-05-04T13:17:00+05:45",
      "confidence": "inferred"
    },
    {
      "category": "Permits",
      "title": "ACAP permit (Annapurna Conservation Area)",
      "detail": "SAARC NPR 1,000/person, single entry, tax included. Foreigners NPR 3,000/person. Buy online at epermit.ntnc.org.np (Visa/MasterCard +2.9% gateway) or at counters in Kathmandu / Pokhara / Simpani / Ghasa. Issuing AT a check-post inside ACAP costs DOUBLE — always buy in Pokhara before driving up. Indian SAARC: Aadhaar OR Voter ID accepted in lieu of passport.",
      "source": "https://epermit.ntnc.org.np/",
      "fetchedAt": "2026-05-04T07:44:00+05:45",
      "confidence": "official"
    },
    {
      "category": "Permits",
      "title": "Lower vs Upper Mustang boundary",
      "detail": "Lower Mustang (open zone, ACAP only): Jomsom, Kagbeni, Muktinath. Kagbeni HAS NOT been reclassified into restricted area. Upper Mustang (restricted): Lomanthang Rural Municipality wards 1–5, Lo-Ghekar Damodarkunda RM wards 1–5, Baragung Muktichetra RM ward 3 + Satang village in ward 5. Restricted boundary begins NORTH of Kagbeni. For Muktinath darshan: ACAP only, no Upper Mustang permit needed.",
      "source": "https://www.immigration.gov.np/page/trekking-route-and-permit-fee",
      "fetchedAt": "2026-05-04T07:46:00+05:45",
      "confidence": "official"
    },
    {
      "category": "Permits",
      "title": "Upper Mustang permit cost (NOT NEEDED)",
      "detail": "USD 50 per person per day, flat. The pre-2025 'USD 500 first 10 days then USD 50/day' structure has been replaced. Issued by Department of Immigration Kalikasthan KTM (or Pokhara office) via licensed trekking agency. NOT needed for this trip — Jomsom/Muktinath are Lower Mustang.",
      "source": "https://www.immigration.gov.np/page/trekking-route-and-permit-fee",
      "fetchedAt": "2026-05-04T07:46:00+05:45",
      "confidence": "official"
    },
    {
      "category": "Permits",
      "title": "TIMS card NOT required for road Jomsom-Muktinath",
      "detail": "TIMS is mandatory only on listed trekking routes. For Mustang region, TIMS is required ONLY for 'Upper Mustang Trek' and 'Sarebung Pass Trek' per NTB Revised TIMS Provision (effective 31 Mar 2023). Lower Mustang road journey to Jomsom/Muktinath is NOT in the list. SAARC TIMS would be NPR 1,000/person if needed; sold only via licensed trekking agencies.",
      "source": "https://ntb.gov.np/plan-your-trip/before-you-come/tims-card",
      "fetchedAt": "2026-05-04T07:46:00+05:45",
      "confidence": "official"
    },
    {
      "category": "Altitude",
      "title": "Muktinath at 3,800 m — AMS risk",
      "detail": "Acclimatise at Jomsom (2,720 m) overnight before Muktinath darshan. Diamox prophylaxis 24h before ascent. Watch for ataxia, breathlessness, severe headache — descend immediately if seen. Manipal Pokhara is the nearest competent altitude care.",
      "source": "https://www.indembkathmandu.gov.in/page/advisory-list/",
      "fetchedAt": "2026-05-04T13:17:00+05:45",
      "confidence": "inferred"
    },
    {
      "category": "Restricted",
      "title": "Drones and sat phones",
      "detail": "Drones rarely permitted (require CAAN clearance + ACAP signoff for the conservation area). Sat phones banned without prior permit. Leave both at home. No 2026 update — carried forward.",
      "source": "https://www.immigration.gov.np/",
      "fetchedAt": "2026-05-04T13:14:00+05:45",
      "confidence": "inferred"
    }
  ],
  "emergencies": [
    {
      "label": "Indian Embassy Kathmandu — General reception",
      "phone": "+977-1-4423702"
    },
    {
      "label": "Indian Embassy Kathmandu — 24×7 emergency",
      "phone": "+977-9851316807"
    },
    {
      "label": "Indian Embassy Kathmandu — Consular grievances",
      "phone": "+977-1-4411466"
    },
    {
      "label": "Indian Embassy Kathmandu — Email",
      "email": "cons.kathmandu@mea.gov.in"
    },
    {
      "label": "Nepal Police",
      "phone": "100"
    },
    {
      "label": "Nepal Ambulance",
      "phone": "102"
    },
    {
      "label": "CIWEC Hospital, Kathmandu",
      "note": "Travel medicine specialist; Pokhara branch too."
    },
    {
      "label": "Manipal Teaching Hospital, Pokhara",
      "note": "Large, English-speaking, altitude-aware."
    }
  ]
};

window.CHECKLIST = {
  "categories": [
    {
      "id": "vehicle-docs",
      "title": "Vehicle Documents",
      "icon": "car",
      "note": "Source folder for firm papers: /Users/sunny/thar/jonga. e-RC + auth letter already laminated. TDS = sole prop on mom's PAN, so auth letter must be signed by mom (proprietor of record), not Shive.",
      "items": [
        {
          "id": "v1",
          "label": "e-RC — laminated copy (already prepared)"
        },
        {
          "id": "v2",
          "label": "Insurance certificate valid 9–23 May (Nepal rider OR plan to buy at border)"
        },
        {
          "id": "v3",
          "label": "PUC certificate valid through 23 May"
        },
        {
          "id": "v4",
          "label": "Driving Licence — Shive (physical + DigiLocker)"
        },
        {
          "id": "v5",
          "label": "Driving Licence — Wife (backup driver)"
        },
        {
          "id": "v6",
          "label": "Authorization Letter — laminated, verified ✓ (mom-signed, Nepal-specific non-commercial language, notary stamp)"
        },
        {
          "id": "v7",
          "label": "Mom's PAN copy — self-attested by her (from /Users/sunny/thar/jonga)"
        },
        {
          "id": "v8",
          "label": "Mom's Aadhaar copy — self-attested by her (from /Users/sunny/thar/jonga)"
        },
        {
          "id": "v9",
          "label": "Relationship proof — Shive's Aadhaar shows mom as parent OR birth certificate"
        },
        {
          "id": "v10",
          "label": "Firm registration / GST certificate (from /Users/sunny/thar/jonga)"
        },
        {
          "id": "v11",
          "label": "Last service slip"
        },
        {
          "id": "v12",
          "label": "Spare key (separate bag, NOT glovebox)"
        }
      ]
    },
    {
      "id": "personal-docs",
      "title": "Personal Documents",
      "icon": "id",
      "note": "Indians don't need a passport for Nepal but it's the preferred ID at hotels and exchange counters.",
      "items": [
        {
          "id": "p1",
          "label": "Passport (preferred) + Voter ID + Aadhaar — both travellers"
        },
        {
          "id": "p2",
          "label": "2 photocopies of each ID (both travellers)"
        },
        {
          "id": "p3",
          "label": "6 passport photos each"
        },
        {
          "id": "p4",
          "label": "Hotel booking confirmations — printed"
        },
        {
          "id": "p5",
          "label": "Travel insurance with mountain medical evacuation"
        },
        {
          "id": "p6",
          "label": "Emergency contacts card (embassy, family, blood group)"
        }
      ]
    },
    {
      "id": "border",
      "title": "Border, Customs & Permits",
      "icon": "border",
      "note": "Complete Bhansar + Yatayat the day you cross at Sunauli. Pay 2–3 buffer days.",
      "items": [
        {
          "id": "b1",
          "label": "Bhansar (Customs) permit — buy with 2–3 day buffer"
        },
        {
          "id": "b2",
          "label": "Yatayat (Transport) permit — buy with 2–3 day buffer"
        },
        {
          "id": "b3",
          "label": "Customs declaration for both MacBook Pros (carry invoices)"
        },
        {
          "id": "b4",
          "label": "ACAP permit (NPR 1,000/person SAARC) — at Pokhara NTB office"
        },
        {
          "id": "b5",
          "label": "TIMS card — only if any trekking planned"
        },
        {
          "id": "b6",
          "label": "Note 30-day cumulative count in phone (this trip = ~17–18 with buffer)"
        }
      ]
    },
    {
      "id": "money",
      "title": "Money",
      "icon": "money",
      "note": "INR 2000 notes are NOT accepted in Nepal. Mustang region = cash-only.",
      "items": [
        {
          "id": "m1",
          "label": "INR cash (100/200/500 notes only) — minimum INR 50,000"
        },
        {
          "id": "m2",
          "label": "Exchange ~INR 30,000 → NPR at Bhairahawa/Pokhara (keep receipts)"
        },
        {
          "id": "m3",
          "label": "Debit card with international withdrawal flag enabled"
        },
        {
          "id": "m4",
          "label": "One Visa/Mastercard credit card"
        },
        {
          "id": "m5",
          "label": "Try eSewa / Khalti setup (Nepali UPI)"
        }
      ]
    },
    {
      "id": "hardware",
      "title": "Connectivity & Hardware (Workation)",
      "icon": "laptop",
      "note": "Two MacBook Pros + invoices to defend personal-use customs status.",
      "items": [
        {
          "id": "h1",
          "label": "MacBook Pro #1 + invoice"
        },
        {
          "id": "h2",
          "label": "MacBook Pro #2 + invoice"
        },
        {
          "id": "h3",
          "label": "2 chargers + 1 spare GaN"
        },
        {
          "id": "h4",
          "label": "USB-C hub (HDMI + Ethernet)"
        },
        {
          "id": "h5",
          "label": "External SSD (1 TB encrypted) — pre-trip backup of Kotlin/Spring/Vue.js repos"
        },
        {
          "id": "h6",
          "label": "NTC tourist SIM (better Mustang coverage) — at Bhairahawa, 2 photos + ID"
        },
        {
          "id": "h7",
          "label": "Ncell SIM (better Pokhara speeds)"
        },
        {
          "id": "h8",
          "label": "Power bank ≥ 20,000 mAh"
        },
        {
          "id": "h9",
          "label": "Travel adapter"
        },
        {
          "id": "h10",
          "label": "Maps.me + Google Maps offline regions downloaded"
        },
        {
          "id": "h11",
          "label": "Headphones + webcam tested"
        },
        {
          "id": "h12",
          "label": "VPN client installed and tested"
        }
      ]
    },
    {
      "id": "vehicle-spares",
      "title": "Vehicle Spares & Tools",
      "icon": "tools",
      "note": "Beni–Jomsom is unforgiving. Tow rope and inflator are non-negotiable.",
      "items": [
        {
          "id": "s1",
          "label": "Stepney + jack + wheel spanner (stepney pressure verified)"
        },
        {
          "id": "s2",
          "label": "12V tyre inflator"
        },
        {
          "id": "s3",
          "label": "Tubeless puncture plug kit"
        },
        {
          "id": "s4",
          "label": "Jumper cables"
        },
        {
          "id": "s5",
          "label": "Tow rope"
        },
        {
          "id": "s6",
          "label": "Spanner / screwdriver / pliers set"
        },
        {
          "id": "s7",
          "label": "Engine oil 1 L (correct grade)"
        },
        {
          "id": "s8",
          "label": "Brake fluid top-up bottle"
        },
        {
          "id": "s9",
          "label": "Coolant 1 L"
        },
        {
          "id": "s10",
          "label": "Wiper blades pair"
        },
        {
          "id": "s11",
          "label": "Assorted fuses"
        },
        {
          "id": "s12",
          "label": "Headlamp / torch + spare batteries"
        },
        {
          "id": "s13",
          "label": "Reflective triangle + tow board"
        },
        {
          "id": "s14",
          "label": "Microfibre cloths"
        },
        {
          "id": "s15",
          "label": "4WD low-ratio practiced before trip"
        },
        {
          "id": "s16",
          "label": "Sealed 10 L jerrycan (fill at Beni, NOT at border)"
        }
      ]
    },
    {
      "id": "medical",
      "title": "Medical Kit",
      "icon": "med",
      "note": "Muktinath = 3,800 m. Diamox prescription before departure, consult doctor.",
      "items": [
        {
          "id": "x1",
          "label": "Personal prescription medications (20 days supply)"
        },
        {
          "id": "x2",
          "label": "Diamox prescription + dosing schedule (both travellers)"
        },
        {
          "id": "x3",
          "label": "Paracetamol, Ibuprofen, ORS sachets"
        },
        {
          "id": "x4",
          "label": "Loperamide / Norfloxacin (anti-diarrhoeal)"
        },
        {
          "id": "x5",
          "label": "Antacid (Pantop)"
        },
        {
          "id": "x6",
          "label": "Cetrizine (antihistamine)"
        },
        {
          "id": "x7",
          "label": "Domstal / Avomine (anti-emetic)"
        },
        {
          "id": "x8",
          "label": "Band-aids, Soframycin, Dettol"
        },
        {
          "id": "x9",
          "label": "Crepe bandage + ice gel pack"
        },
        {
          "id": "x10",
          "label": "Sunscreen SPF 50+, lip balm with SPF"
        },
        {
          "id": "x11",
          "label": "Moisturiser, mosquito repellent"
        },
        {
          "id": "x12",
          "label": "Pulse oximeter (clip-on)"
        },
        {
          "id": "x13",
          "label": "Thermos flask"
        }
      ]
    },
    {
      "id": "clothing",
      "title": "Clothing & Personal",
      "icon": "shirt",
      "note": "Lowland 28–34°C, Mustang mornings 5–10°C, daytime 15–22°C.",
      "items": [
        {
          "id": "c1",
          "label": "Light cottons — 4 sets each"
        },
        {
          "id": "c2",
          "label": "Mid-layer fleece each"
        },
        {
          "id": "c3",
          "label": "Windproof / light down jacket each"
        },
        {
          "id": "c4",
          "label": "Thermal innerwear (1 set) for Muktinath night"
        },
        {
          "id": "c5",
          "label": "Gloves + woollen cap each"
        },
        {
          "id": "c6",
          "label": "Closed walking shoes + sandals"
        },
        {
          "id": "c7",
          "label": "Cap + UV400 sunglasses"
        },
        {
          "id": "c8",
          "label": "Rain shell"
        },
        {
          "id": "c9",
          "label": "Toiletries + quick-dry towel"
        },
        {
          "id": "c10",
          "label": "Eye-mask + earplugs"
        }
      ]
    },
    {
      "id": "pre-departure",
      "title": "Pre-departure Tasks (before 9 May)",
      "icon": "clock",
      "note": "Lock these by 2026-05-07.",
      "items": [
        {
          "id": "d1",
          "label": "Full Thar Roxx service (by 7 May)"
        },
        {
          "id": "d2",
          "label": "FASTag balance ≥ INR 5,000"
        },
        {
          "id": "d3",
          "label": "Inform bank / cards of Nepal travel"
        },
        {
          "id": "d4",
          "label": "Backup work repos to SSD + cloud"
        },
        {
          "id": "d5",
          "label": "Out-of-office / limited-connectivity auto-reply set"
        },
        {
          "id": "d6",
          "label": "Block work calendar 9–23 May; pre-schedule deliverables"
        },
        {
          "id": "d7",
          "label": "Notify family of route + emergency contacts"
        },
        {
          "id": "d8",
          "label": "Doctor consult for Diamox"
        },
        {
          "id": "d9",
          "label": "Print every doc twice + photograph all to Drive/iCloud"
        },
        {
          "id": "d10",
          "label": "Test 4WD low-ratio on a quiet road"
        }
      ]
    },
    {
      "id": "daily",
      "title": "Daily Discipline (during trip)",
      "icon": "checks",
      "note": "Quiet daily habits that save you from large problems later.",
      "items": [
        {
          "id": "y1",
          "label": "Photograph all permits + receipts daily"
        },
        {
          "id": "y2",
          "label": "Update Nepal cumulative-day count"
        },
        {
          "id": "y3",
          "label": "Log fuel + odometer at each fill-up"
        },
        {
          "id": "y4",
          "label": "≥ 3 L water/day above Beni"
        },
        {
          "id": "y5",
          "label": "No alcohol night before Muktinath"
        },
        {
          "id": "y6",
          "label": "Charge MacBooks + power bank every evening"
        },
        {
          "id": "y7",
          "label": "Cloud-sync work in Pokhara before any Mustang leg"
        }
      ]
    },
    {
      "id": "return",
      "title": "Return Day (Saturday 23 May)",
      "icon": "home",
      "note": "Closing the loop matters — for the day-count and for any future audit.",
      "items": [
        {
          "id": "r1",
          "label": "Surrender Bhansar + Yatayat at Sunauli — get exit stamp"
        },
        {
          "id": "r2",
          "label": "Keep all Nepal receipts for 6 months"
        },
        {
          "id": "r3",
          "label": "Re-fuel before crossing back"
        },
        {
          "id": "r4",
          "label": "Photograph odometer at border + at home"
        }
      ]
    }
  ]
};
