#!/usr/bin/env python3
"""
Regenerate the website's bundled JS data files.
Run this whenever you've edited /data/*.json or any .md under /docs/, /plans/, /claude-code/.

  python3 website/build.py

Outputs:
  website/js/data.js  — TRIP, ITINERARY, RULES, CHECKLIST (from /data/*.json)
  website/js/docs.js  — DOCS dict mapping repo-relative path to markdown source
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent  # repo root
WEBSITE_JS = ROOT / "website" / "js"

# ---------------- data.js ----------------
def build_data_js() -> None:
    rules     = json.load(open(ROOT / "data" / "rules.json"))
    itinerary = json.load(open(ROOT / "data" / "itinerary.json"))
    checklist = json.load(open(ROOT / "data" / "checklist.json"))

    trip = {
        "name": "Nepal Workation 2026",
        "depart": "2026-05-09",
        "return": "2026-05-23",
        "nights": 14,
        "travellers": 2,
        "vehicle": "Mahindra Thar Roxx (Thar Digital Services — sole prop on mom's PAN)",
        "capDays": 30,
        "permitDaysUsed": 18,
        "totalKm": 4410,
    }

    out = (
        "/* Auto-generated by website/build.py — do not hand-edit. */\n\n"
        "window.TRIP = "      + json.dumps(trip,                indent=2, ensure_ascii=False) + ";\n\n"
        "window.ITINERARY = " + json.dumps(itinerary["days"],   indent=2, ensure_ascii=False) + ";\n\n"
        "window.RULES = "     + json.dumps(rules,               indent=2, ensure_ascii=False) + ";\n\n"
        "window.CHECKLIST = " + json.dumps(checklist,           indent=2, ensure_ascii=False) + ";\n"
    )
    (WEBSITE_JS / "data.js").write_text(out)
    print(f"  data.js   → {len(out):>6} bytes")


# ---------------- docs.js ----------------
# Folders we expose to the viewer. Add/remove entries here.
DOC_DIRS = [
    ("docs",          "Reference docs"),
    ("plans",         "Your trip-plan space"),
    ("claude-code",   "Claude Code briefing"),
]
# Files we explicitly skip (fragments, large logs, sensitive things).
SKIP_NAMES = {".gitkeep"}

def build_docs_js() -> None:
    docs = {}      # path → markdown content
    sections = {}  # display label → list of {path, title, dir}

    for folder, label in DOC_DIRS:
        folder_path = ROOT / folder
        if not folder_path.exists():
            continue
        files = sorted(folder_path.rglob("*.md"))
        for f in files:
            if f.name in SKIP_NAMES:
                continue
            rel = f.relative_to(ROOT).as_posix()
            content = f.read_text()
            docs[rel] = content
            # title = first H1 line if present, else filename
            title = None
            for line in content.splitlines()[:8]:
                line = line.strip()
                if line.startswith("# "):
                    title = line[2:].strip()
                    break
            if not title:
                title = f.stem.replace("-", " ").replace("_", " ").title()
            sections.setdefault(label, []).append({
                "path": rel,
                "title": title,
                "dir": f.parent.relative_to(ROOT).as_posix(),
            })

    # stable order of sections per DOC_DIRS
    ordered_sections = [(lbl, sections.get(lbl, [])) for _, lbl in DOC_DIRS]

    out = (
        "/* Auto-generated by website/build.py — do not hand-edit.\n"
        "   Bundles the markdown content of /docs, /plans, /claude-code so the\n"
        "   viewer works when index.html is opened directly from the filesystem\n"
        "   (file:// fetch is blocked by some browsers). */\n\n"
        "window.DOCS = "     + json.dumps(docs,             indent=2, ensure_ascii=False) + ";\n\n"
        "window.DOC_INDEX = "+ json.dumps(ordered_sections, indent=2, ensure_ascii=False) + ";\n"
    )
    (WEBSITE_JS / "docs.js").write_text(out)
    total_md_kb = sum(len(c) for c in docs.values()) / 1024
    print(f"  docs.js   → {len(out):>6} bytes ({len(docs)} files, {total_md_kb:.1f} KB of MD)")


if __name__ == "__main__":
    print("rebuilding bundled site data...")
    build_data_js()
    build_docs_js()
    print("done.")
